### ISSUE TITLE
Add Python Setup Instructions to Github

### ISSUE THREAD

**Issue by M-Anwar** [M-Anwar/ARGEL#4]
Is it possible to add a wiki page outlining the setup of required modules for python @S-Farooq ? Just outlining which modules (openCV, scipy, numpy etc.) are required to get things running. This would be useful when we setup a separate server and need to install our application @kimjon12 .

**Comment by S-Farooq** [comment]
Added some stuff, is this what you meant or something more?

**Comment by M-Anwar** [comment]
Yes awesome should be enough for @kimjon12 to work with getting our stuff on a server
